# check if vip is being used
- name: ping keepalived_vip
  shell: ping -c 1 {{ keepalived_vip }}; if [ $? -ne 0 ]; then exit 0; else exit 1; fi;
  register: ping_result
  delegate_to: 127.0.0.1
  run_once: true
  ignore_errors: true
- name: keepalived vip not used
  fail:
    msg: "ip exists"
  when: ping_result.failed

# install keepalived
- name: copy keepalived rpms to nodes
  copy:
    src: keepalived/
    dest: /root/keepalived/
- name: install keepalived
  shell: rpm -i --force --nodeps /root/keepalived/*rpm

- name: check if /root/keepalived.conf is exists
  stat:
    path: /root/keepalived.conf.bak
  register: file_stat
- name: backup /etc/keepalived/keepalived.conf to /root/keepalived.conf.bak
  shell: mv /etc/keepalived/keepalived.conf /root/keepalived.conf.bak
  when: not file_stat.stat.exists

- name: copy keepalived.conf.j2 to /etc/keepalived/keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
- name: copy check_port.sh /etc/keepalived/
  copy:
    src: scripts/check_port.sh
    dest: /etc/keepalived/check_port.sh
    mode: "0755"

- name: systemctl enable keepalived.service --now
  shell: systemctl enable keepalived.service --now

- name: systemctl restart keepalived.service
  shell: systemctl restart keepalived.service
