- include: 01.2_install_docker.yml

# copy k8s certificate to nodes
- name: mkdir /etc/kubernetes/pki/
  file:
    path: /etc/kubernetes/pki/
    state: directory
- name: copy cert/k8s/ to /etc/kubernetes/pki/
  copy:
    src: cert/k8s/
    dest: /etc/kubernetes/pki/

# delete 10-containerd-net.conflist
# If the Pod IP shows 10.88.0.0, remove the file /etc/cni/net.d/10-containerd-net.conflist, 
# please refer to https://zhuanlan.zhihu.com/p/608369342
- name: delete /etc/cni/net.d/10-containerd-net.conflist
  file:
    path: /etc/cni/net.d/10-containerd-net.conflist
    state: absent

- include: 08.2_install_kubelet_docker.yml
- include: 09_install_kube_proxy.yml
